version: '3'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
     - redis-network
    volumes:
     - ./redis-dados:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
     REDIS_HOSTS: local:redis:6379
     REDIS_HOST: redis
     REDIS_PORT: redis:6379
     REDIS_PASSWORD: redis
     HTTP_USER: root
     HTTP_PASSWORD: root
    ports:
    - "8081:8081"
    networks:
     - redis-network

networks:
  redis-network:
    driver: bridge